# Generated by Django 4.0.6 on 2022-07-19 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('image', models.ImageField(upload_to='category/')),
                ('icon', models.ImageField(upload_to='category/')),
                ('post_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=128, verbose_name='Post Nomi: ')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('content', models.TextField()),
                ('description', models.CharField(max_length=128)),
                ('image', models.ImageField(upload_to='posts/')),
                ('published_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('created', 'created'), ('moderation', 'moderation'), ('published', 'published')], max_length=15)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('is_popular', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='author.author')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.category')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
