# Generated by Django 4.0.6 on 2022-07-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=128, verbose_name='Ism: ')),
                ('last_name', models.CharField(max_length=128, verbose_name='Familya: ')),
                ('slug', models.CharField(max_length=128, unique=True)),
                ('username', models.CharField(max_length=128, verbose_name='Username: ')),
                ('avatar', models.ImageField(upload_to='author/')),
                ('user_type', models.CharField(choices=[('user', 'user'), ('company', 'company'), ('author', 'author'), ('lenta', 'lenta')], max_length=15)),
                ('bio', models.TextField()),
                ('content', models.TextField()),
                ('post_count', models.IntegerField(default=0)),
                ('comment_count', models.IntegerField(default=0)),
                ('follower_count', models.IntegerField(default=0)),
                ('is_top', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
